INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (1, 'Florence Ledford','1972-01-21',46,'Miami','FL','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (2, 'Sarah Araujo','1970-02-28',4848,'Santo Antônio de Jesus','BA','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (3, 'Victoria Anderson','1940-11-15',77,'Oklahoma City','OK','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (4, 'Murilo Costa','2016-01-18',2,'São Paulo','SP','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (5, 'Júlia Goncalves','1929-04-03',89,'Eunápolis','BA','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (6, 'Isabella Costa','1951-04-10',67,'Gainesville','GA','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (7, 'Bruce Dillard','2012-06-01',6,'Santa Ana','CA','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (8, 'James Jensen','1955-12-23',62,'Campo Largo','PR','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (9, 'André Rodrigues','1980-05-04',38,'Indaiatuba','SP','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (10, 'Carl Gonzalez','1920-12-21',97,'Kemblesville','PA','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (11, 'Júlio Pinto','1991-03-30',27,'New York','NY','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (12, 'Jeffery McGann','2004-08-26',13,'Dallas','TX','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (13, 'John Davis','1948-02-14',70,'Salvador','BA','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (14, 'Giovanna Sousa','1981-07-28',36,'Honolulu','HI','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (15, 'Miguel Pinto','1928-04-29',90,'Huntsville','AL','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (16, 'Luann Harrison','1934-09-17',83,'Orem','UT','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (17, 'Aline Goncalves','1985-05-08',33,'Charlotte','NC','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (18, 'Bianca Correia','1941-12-01',76,'Teresópolis','RJ','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (19, 'Gabriel Martins','1951-01-14',67,'Lexington','KY','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (20, 'Patricia Parker','1971-02-04',47,'Florianópolis','SC','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (21, 'Catherine Taing','1932-04-23',86,'São Paulo','SP    ','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (22, 'Fernanda Azevedo','1994-12-27',23,'Fortaleza','CE','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (23, 'Penny Plowman','1968-08-06',49,'Goiânia','GO','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (24, 'Erick Ferreira','1986-10-26',31,'Curitiba','PR','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (25, 'Reginald Ohler','1961-04-09',57,'Dourados','MS','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (26, 'Joseph Reveles','1926-03-28',92,'Dallas','TX','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (27, 'Karyl Briggs','1999-04-29',19,'Killeen','TX','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (28, 'Susan Morgan','2005-07-26',12,'Longview','WA','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (29, 'George Bollinger','1933-08-07',84,'New York','NY','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (30, 'Erick Azevedo','1924-05-31',94,'Las Vegas','NV','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (31, 'Mandy Dotson','1989-11-28',28,'Easton','MD','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (32, 'Rodrigo Correia','1936-04-29',82,'Cruzeiro','DF','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (33, 'Gary Wright','1926-03-13',92,'Orlando','FL','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (34, 'Lewis Payne','1967-06-27',50,'Toledo','OH','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (35, 'Erick Azevedo','1938-02-25',80,'Louisville','KY','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (36, 'Joseph Darwin','1967-01-03',51,'Rio de Janeiro','RJ','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (37, 'Bianca Barbosa','1996-02-29',22,'Grand Rapids','MI','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (38, 'Julia Ferreira','2005-12-17',12,'Vitória de Santo Antão','PE','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (39, 'Liliana Castillo','1930-09-19',87,'Porto Alegre','RS','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (40, 'Brenda Souza','1996-03-19',22,'Rio de Janeiro','RJ','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (41, 'Yasmin Azevedo','2003-05-11',15,'Varginha','MG','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (42, 'Kathleen Wilson','1956-09-28',61,'Cachoeira do Sul','RS','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (43, 'Tabatha Chaffee','1919-08-05',98,'West Warwick','RI','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (44, 'Letícia Goncalves','2005-10-27',12,'Parintins','AM','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (45, 'Erick Cunha','1989-09-04',28,'Fort Myers','FL','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (46, 'David McNally','1995-01-27',23,'Taubaté','SP','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (47, 'Luis Martins','1996-01-03',22,'São Paulo','SP','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (48, 'Judith Gantt','1921-09-16',96,'Manaus','AM','A' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (49, 'Leila Cunha','1942-08-31',75,'Getzville','NY','D' );
INSERT INTO clients (id, name, date_birthday, age, city, state, active) VALUES (50, 'Eduarda Gomes','1924-12-27',93,'Taos','NM','A' );
